content:
  - name: page2
    label: Hoodie 2
    type: file
    path: 2/content.json
    fields:
      - name: headline
        label: Kleine Überschrift
        type: string

      - name: title
        label: Große Überschrift
        type: string

      - name: text
        label: Haupttext
        type: text

      - name: greeting
        label: Grußzeile
        type: string

      - name: ps
        label: PS
        type: string